import type { AnalysisResult } from "../analysis/pipeline";
import type { PlotAnalysis } from "../analysis/schema";
import type { CharacterAnalysis } from "../analysis/schema";

/**
 * Mock 数据 — 拆文+人设分析演示
 *
 * 样例：一篇悬疑短篇，关于收到亡父来信的调查故事。
 */

// ===== 原文 =====
export const MOCK_PARAGRAPHS: string[] = [
  "信封躺在门口脚垫上，没有邮票，没有寄件人，只有我的名字——写错了。",
  "我把信封捡起来，指腹摩挲过粗糙的纸面。门内的电话突然响了三声，又断了。",
  "我拆开信。一张白纸，中央只有一行字：你父亲不是意外死的。窗外的风停了。",
  "父亲去世已经七年。警方说是山道滑坡，连车带人翻下了崖。我亲眼见过那辆被压扁的车。",
  "我开始翻找旧物。父亲的笔记本里夹着一张加油站的收据，日期是他出事那天，地点却在三百公里外。",
  "我拨通当时处理事故的交警老周。电话那头沉默了很久，最后他说：有些事，你别查了。",
  "深夜，我又收到一封信。这次寄件人栏写着父亲的名字，邮戳是七年前。",
  "我驱车去那个加油站。老板认出了收据，说那天确实有个男人来过，上车前回头看了三次。",
  "回程的山道上，后视镜里出现了一辆黑色轿车。它跟我保持两百米，整整四十分钟。",
  "我把车停在路边。黑色轿车驶过，车窗降下一半——是老周。他没有看我。",
  "我继续往山上开。雨开始下。在父亲出事那个弯道，我踩下了刹车。",
  "崖底没有车的残骸，只有一束新放的白色雏菊，花瓣上还沾着露水。",
  "手机亮了。一条未知号码的短信：你查得太快了。现在，轮到我找你。",
];

// ===== 拆文分析 mock =====
const MOCK_PLOT: PlotAnalysis = {
  editorView: {
    basicInfo: {
      title: "亡父来信",
      platform: "知乎盐言故事",
      wordCount: "约 612 字",
      type: "悬疑/推理短篇",
      tags: "悬疑、亡父、来信、反转、山道",
      oneLineSummary:
        "因为收到一封没有寄件人的信，主人公被未知势力以'亡父死因疑点'推入恐惧与追查的处境，当主人公发现加油站收据和交警老周的异常后，选择独自驱车前往山道调查，最终让真相在崖底的白色雏菊中浮现，完成从被动接受到主动追查的认知反转。",
      readerAttraction: "第一句'写错的名字'立刻制造悬念——谁在监视？为什么连名字都错？",
      worthTeardownReason: "导语钩子极强，信息差层层递进，付费点卡在'轮到我找你'的认知反转上，适合拆解悬疑短篇的情绪拉扯手法。",
    },
    guideAnalysis: {
      exists: true,
      boundaryJudgment: "前三段为功能性导语，在'父亲去世已经七年'之前完成钩子铺设。",
      highlights: [
        "'写错的名字'制造即时悬念",
        "白纸一行字打破认知",
        "电话三声后断掉制造不安",
      ],
      protagonistIdentity: "独居的亡父子女，七年未走出丧父之痛",
      antagonist: "未知势力（逐步揭示为交警老周及其背后的人）",
      firstConflict: "信中声称'父亲不是意外死的'与警方结论矛盾",
      painPoint: "丧父七年的未愈合创伤被重新撕开",
      satisfactionPoint: "真相逐步揭开带来的认知快感",
      readerCuriosity: "父亲到底怎么死的？老周为什么说'别查了'？谁在监视主人公？",
      isCatchy: true,
    },
    sentenceAnalysis: [
      {
        sentence: "信封躺在门口脚垫上，没有邮票，没有寄件人，只有我的名字——写错了。",
        function: "用三个否定（没有邮票、没有寄件人、写错了）叠加制造异常感，'写错的名字'是第一个钩子，让读者立刻追问：谁在监视？为什么连名字都错？同时交代了主人公的独居处境。",
      },
      {
        sentence: "我把信封捡起来，指腹摩挲过粗糙的纸面。门内的电话突然响了三声，又断了。",
        function: "用触觉描写（粗糙的纸面）增加沉浸感，电话三声后断掉制造即时不安，暗示有人在试探主人公的反应，同时制造了第二个悬念。",
      },
      {
        sentence: "我拆开信。一张白纸，中央只有一行字：你父亲不是意外死的。窗外的风停了。",
        function: "核心钩子句。'白纸中央一行字'制造视觉冲击，'你父亲不是意外死的'直接颠覆主人公和读者的认知，'窗外的风停了'用环境描写强化凝固的恐惧感，承诺后续爽点：真相揭开。",
      },
    ],
    guideReview: {
      firstSentenceCatchy: true,
      quickProtagonist: true,
      quickRelations: true,
      quickConflict: true,
      strongContrast: true,
      clearPainPoint: true,
      promisesSatisfaction: true,
      holdsQuestion: true,
      mostValuableSentence: "你父亲不是意外死的。窗外的风停了。",
      deletableSentence: "门内的电话突然响了三声，又断了。（可删，因信息量与信封重叠）",
      guideModel: "用异常物件+颠覆性信息+环境凝固制造即时悬念，承诺真相揭开。",
    },
    entryPoint: {
      firstChapterEvent: "翻找旧物发现加油站收据，日期和地点与事故矛盾",
      connectsGuide: true,
      amplifiesConflict: true,
      establishesRelations: true,
      givesDirection: true,
    },
    payPoint: {
      position: "最后一段'轮到我找你'处",
      precedingConflict: "崖底没有车残骸只有新放的雏菊",
      cardType: "悬念+身份掉马",
      naturallyGrown: true,
      infoGapRemaining: true,
      readerWaiting: true,
    },
    deepTeardownJudgment: {
      entryExplosive: "切入点够炸，'亡父来信'本身就有强烈吸引力",
      antagonistDistinctive: "老周作为隐藏反派有辨识度，'别查了'一句立住人设",
      payPointNatural: "付费点从加油站→跟踪→山道→崖底自然递进",
      platformMatch: "知乎盐言故事调性匹配，悬疑+短篇+反转",
      conclusion: "建议深拆",
      reason: "导语钩子极强，信息差递进清晰，付费点卡点自然，适合拆解悬疑短篇的情绪拉扯和信息差设计手法。",
    },
  },
  sixCoreElements: {
    pace: {
      speed: "快节奏推进，每段都有新信息或新悬念",
      mainStuckPoints: ["加油站收据与事故矛盾", "老周说'别查了'", "黑色轿车跟踪"],
      fastParts: ["前三段导语", "崖底发现雏菊"],
      slowParts: ["驱车前往加油站途中（可加压）"],
      chapterEndHooks: true,
    },
    framework: {
      coreAttractionType: "悬念驱动型",
      bigFramework: "异常物件→调查→发现矛盾→追查→真相浮现",
      setup: "收到亡父来信，信中声称父亲非意外死亡",
      development: "发现加油站收据矛盾，老周警告'别查了'",
      turn: "山道被跟踪，崖底发现雏菊而非车残骸",
      conclusion: "收到威胁短信'轮到我找你'",
      unchangeablePart: "信中'父亲不是意外死的'这一核心颠覆，后续所有调查都由此驱动",
    },
    protagonist: {
      surfaceIdentity: "独居的亡父子女",
      deepSituation: "七年未走出丧父创伤，对父亲死因有深层执念",
      painPoint: "丧父七年的未愈合创伤",
      desire: "查明父亲真实死因",
      bottomLine: "不能接受父亲死因是谎言",
      counterAbility: "观察力强（发现收据矛盾），行动力强（独自驱车调查）",
      firstEstablishEvent: "翻找旧物发现加油站收据——体现观察力和执念",
      highlightAction: "在暴雨中继续开往山道，明知被跟踪仍不退缩",
    },
    antagonist: {
      surfaceIdentity: "处理事故的交警老周",
      harmMethod: "用'别查了'进行言语压制，用跟踪进行行为恐吓",
      misjudgment: "误判主人公会因恐惧而放弃追查",
      readerDislikeReason: "滥用职权隐瞒真相，虚伪地假装关心",
      distinctive: true,
      grounded: true,
    },
    supporting: [
      {
        name: "加油站老板",
        function: "提供关键信息（父亲当天回头看了三次），推动调查进展",
      },
    ],
    painPoint: {
      realPain: "七年信仰的'意外死亡'结论被推翻，父亲可能被害",
      source: "来信+加油站收据的双重证据",
      boundToCharacter: true,
      readerResonance: true,
      layeredDeepening: true,
    },
    satisfactionPoint: {
      type: "认知反转型爽点",
      precedingPain: "丧父创伤+被跟踪恐惧",
      fulfillmentAction: "崖底发现雏菊，证明父亲死因有隐情",
      immediateOrDelayed: "延迟兑现",
      exceedsGuidePromise: true,
      prematureLeak: false,
    },
    infoGap: {
      whoKnows: "老周（及背后势力）知道父亲真实死因",
      whoDoesntKnow: "主人公不知道",
      readerKnowsWhen: "读者和老周同步知道'别查了'暗示有隐情，但不知道具体真相",
      payPointRevealsWhen: "最后一段'轮到我找你'暗示老周就是施害者之一",
    },
  },
  plotEmotionFlow: {
    payPointPosition: "最后一段",
    cardType: "悬念+身份掉马",
    coreExpectation: "想知道父亲到底怎么死的，老周是谁",
    releaseDirection: "真相揭开+威胁升级",
    guidePromiseCaught: true,
    chaptersBeforePayPoint: [
      {
        chapter: "导语（1-3段）",
        overallProgress: "用来信制造即时悬念，颠覆'意外死亡'认知",
        conflictProgress: "信中信息与警方结论矛盾",
        emotionPull: "好奇+不安",
        endingHook: "窗外的风停了——恐惧凝固",
      },
      {
        chapter: "调查（4-8段）",
        overallProgress: "发现加油站收据矛盾，老周警告，第二封信升级",
        conflictProgress: "证据指向非意外，老周从旁观者转为阻碍者",
        emotionPull: "紧张+愤怒",
        endingHook: "加油站老板说'回头看了三次'——预感不妙",
      },
      {
        chapter: "对峙（9-12段）",
        overallProgress: "被跟踪，山道暴雨，崖底发现雏菊",
        conflictProgress: "跟踪者身份揭露（老周），崖底无车残骸推翻事故结论",
        emotionPull: "恐惧+震惊",
        endingHook: "崖底只有雏菊——真相呼之欲出",
      },
    ],
    chapterEvents: [
      {
        chapter: "导语",
        events: [
          {
            event: "悬念点1",
            content: "收到写错名字的无邮票信封，主人公发现被监视",
            emotionPlotRole: "制造即时不安，读者好奇谁在监视",
          },
          {
            event: "信息点1",
            content: "信中白纸一行字'你父亲不是意外死的'，颠覆认知",
            emotionPlotRole: "核心钩子，读者震惊，期待真相",
          },
        ],
      },
      {
        chapter: "调查",
        events: [
          {
            event: "信息点1",
            content: "父亲笔记本里的加油站收据，日期是出事当天，地点在三百公里外",
            emotionPlotRole: "证明父亲死因有疑点，读者紧张升级",
          },
          {
            event: "卡点1",
            content: "老周说'有些事你别查了'，从旁观者转为阻碍者",
            emotionPlotRole: "读者愤怒+不安，老周身份可疑",
          },
          {
            event: "悬念点1",
            content: "第二封信寄件人是父亲，邮戳是七年前",
            emotionPlotRole: "时间逻辑崩塌，读者困惑升级",
          },
          {
            event: "信息点2",
            content: "加油站老板认出收据，说父亲上车前回头看了三次",
            emotionPlotRole: "父亲似有预感，读者心酸+紧张",
          },
        ],
      },
      {
        chapter: "对峙",
        events: [
          {
            event: "悬念点1",
            content: "后视镜出现黑色轿车，跟踪四十分钟",
            emotionPlotRole: "恐惧升级，读者紧张到极点",
          },
          {
            event: "反转点1",
            content: "黑色轿车车窗降下，是老周，他没有看主人公",
            emotionPlotRole: "老周身份揭露，读者震惊愤怒",
          },
          {
            event: "反转点2",
            content: "崖底没有车残骸，只有新放的白色雏菊",
            emotionPlotRole: "彻底推翻事故结论，真相呼之欲出",
          },
          {
            event: "卡点1",
            content: "收到短信'你查得太快了。现在，轮到我找你。'",
            emotionPlotRole: "付费点！从追查者变为被追查者，读者必须往下看",
          },
        ],
      },
    ],
    emotionProgressionChain: {
      initialEmotion: "好奇（收到异常信封）",
      firstPressure: "不安（电话三声断掉）",
      secondPressure: "震惊（信中颠覆性信息）",
      thirdPressure: "紧张（发现收据矛盾+老周警告）",
      maxPressure: "恐惧（被跟踪+暴雨山道+崖底雏菊）",
      smallSatisfactions: ["加油站老板提供线索", "确认父亲死因有隐情"],
      falsePromises: ["老周看似关心实则威胁"],
      prematureSatisfaction: [],
      payPointTrigger: "'轮到我找你'——角色反转，从追查者变为被追查者",
    },
    infoGapProgressionChain: {
      knownInfo: "父亲七年前死于山道滑坡（官方结论）",
      hiddenInfo: "父亲当天出现在三百公里外的加油站，崖底没有车残骸",
      misjudgedInfo: "老周是处理事故的交警，看似中立",
      reversalSigns: "老周说'别查了'+跟踪主人公",
      approachingReveal: "崖底雏菊证明有人一直在'祭拜'，老周就是知情者",
      exhaustedEarly: false,
      specificEnough: true,
    },
    chaptersAfterPayPoint: [
      {
        chapter: "后续（待补）",
        mainEvents: "主人公被未知势力追查，必须揭开父亲死因才能自保",
        releaseDirection: "真相揭开+反击",
        role: "兑现'轮到我找你'的威胁升级，读者期待主人公反击",
      },
    ],
    totalReview: {
      guidePromise: "导语承诺：父亲死因有隐情，主人公将追查真相",
      stepByStep: "收据→老周警告→第二封信→加油站线索→跟踪→崖底雏菊，层层递进",
      naturalCardPoint: true,
      strongPayImpulse: true,
      enoughReleaseSpace: true,
      disconnectExists: false,
      cardPointAppearsFromNowhere: false,
      mostReusablePart: "信息差递进链：已知→隐藏→误判→反转苗头→接近揭开，每一步都有具体'事'推动",
    },
  },
  creativeAssets: {
    coreGerm: {
      originalCoreGerm: "亡父来信揭开死亡真相，追查者变为被追查者",
      abstractCoreGerm: "异常信息推翻既定结论，调查者反被猎杀",
      whatItSells: "认知颠覆的快感+从追查到被追查的身份反转恐惧",
      transferableParts: ["信息差递进链", "角色反转付费点", "环境凝固制造悬念"],
      nonTransferableParts: ["亡父+山道+加油站的具体设定", "交警老周的身份"],
      worksAfterGenreChange: true,
    },
    conflictEngine: {
      sustainedBy: "每一步调查都发现新矛盾，矛盾推动下一步调查",
      coreOppression: "老周（及背后势力）对真相的隐瞒和对主人公的监视",
      antagonistLogic: "先用言语压制（'别查了'），再用行为恐吓（跟踪），最后直接威胁",
      protagonistCantSolveImmediately: "因为对手是执法者，掌握资源和信息优势",
      escalationBy: "每次调查都触及更深层真相，对手的压制也随之升级",
      transferableUse: "任何'调查者反被猎杀'的故事都可以用这个发动机",
    },
    emotionFuel: {
      mainEmotion: "恐惧+好奇的交替递进",
      emotionStart: "收到异常信封的好奇",
      pressureBy: "每一步调查都增加危险信号",
      releaseBy: "崖底雏菊的发现给了部分释放（确认有隐情），但马上被'轮到我找你'重新加压",
      bestMigrationTarget: "悬疑/惊悚类短篇，尤其是'调查者反被猎杀'模式",
    },
    satisfactionDelivery: {
      deliveryBy: "认知反转——崖底没有车残骸只有雏菊，推翻事故结论",
      enoughPainBefore: true,
      consistentWithGuide: true,
      exceedsExpectation: true,
      transferableMechanism: "用物件矛盾（无车残骸有雏菊）制造认知反转，不需要长篇解释",
    },
    forbiddenZones: [
      { type: "不能照搬的人物关系", content: "交警作为隐藏反派的具体设定" },
      { type: "不能照搬的具体身份", content: "亡父子女+山道事故+加油站收据" },
      { type: "不能照搬的关键事件", content: "崖底只有雏菊而非车残骸" },
      { type: "不能照搬的场景道具", content: "写错名字的信封+七年前邮戳的信" },
    ],
  },
  masterTable: {
    bookName: "亡父来信",
    genre: "悬疑/推理短篇",
    tags: "悬疑、反转、信息差、角色反转",
    guideModel: "异常物件+颠覆信息+环境凝固",
    coreAttraction: "从追查者变为被追查者的身份反转",
    infoGap: "老周知道真相，主人公不知道，读者逐步同步",
    payCardPoint: "'轮到我找你'——角色反转",
    mainFormula: "异常→调查→矛盾→追查→真相浮现→反转",
    characterMechanism: "观察力强的执念型主人公+滥用职权的隐藏反派",
    painPointEvents: "加油站收据矛盾、老周警告、被跟踪",
    satisfactionEvents: "崖底雏菊发现、老周身份揭露",
    forbiddenZones: "交警身份、亡父+山道+加油站设定、崖底雏菊",
  },
  materialCards: [
    {
      cardName: "核心梗卡",
      cardType: "coreGerm",
      fields: [
        { key: "一句话核心梗", value: "异常信息推翻既定结论，调查者反被猎杀" },
        { key: "可迁移框架", value: "异常物件→调查→矛盾→追查→真相浮现→角色反转" },
        { key: "可替换人物关系", value: "记者与隐藏腐败官员、医生与医药公司、学生与校方" },
        { key: "可替换题材", value: "职场悬疑、校园悬疑、医疗悬疑" },
        { key: "适合生成的新故事方向", value: "实习生发现公司账目异常，调查后反被栽赃" },
      ],
    },
    {
      cardName: "反派行为卡",
      cardType: "antagonistBehavior",
      fields: [
        { key: "反派伤害方式", value: "言语压制+行为恐吓+直接威胁，逐步升级" },
        { key: "反派误判", value: "误判主人公会因恐惧放弃追查" },
        { key: "读者为什么恨", value: "滥用职权、虚伪关心、冷血监视" },
        { key: "可替换场景", value: "医院、学校、企业、政府机关" },
        { key: "可升级方向", value: "反派从个人变为组织，威胁从个人变为全家" },
      ],
    },
    {
      cardName: "开场场景卡",
      cardType: "openingScene",
      fields: [
        { key: "开场触发事件", value: "收到异常物件（写错名字的信封）" },
        { key: "主角处境", value: "独居、七年未走出创伤、信息孤岛" },
        { key: "读者第一情绪", value: "好奇+不安" },
        { key: "可替换场景", value: "收到匿名包裹、发现异常数据、听到异常录音" },
        { key: "可生成导语方向", value: "用异常物件+三个否定制造即时悬念" },
      ],
    },
    {
      cardName: "爽点事件卡",
      cardType: "satisfactionEvent",
      fields: [
        { key: "爽点类型", value: "认知反转型" },
        { key: "爽点前置痛点", value: "被跟踪恐惧+官方结论不可信的无力感" },
        { key: "爽点兑现动作", value: "崖底发现雏菊而非车残骸，彻底推翻事故结论" },
        { key: "读者获得感", value: "确认'有隐情'的满足+期待真相大白的快感" },
        { key: "可迁移方式", value: "用物件矛盾制造认知反转，不需要长篇解释" },
      ],
    },
    {
      cardName: "人设塑造卡",
      cardType: "characterBuilding",
      fields: [
        { key: "人设关键词", value: "执念、观察力、行动力、不畏威胁" },
        { key: "人设确立事件", value: "发现收据矛盾后立刻开始调查" },
        { key: "人设高光动作", value: "暴雨中明知被跟踪仍开往山道" },
        { key: "人设底层逻辑", value: "丧父创伤驱动执念，执念驱动行动力" },
        { key: "可迁移方式", value: "创伤驱动的执念型调查者，可换任何创伤来源" },
      ],
    },
    {
      cardName: "情绪推进卡",
      cardType: "emotionProgress",
      fields: [
        { key: "初始情绪", value: "好奇（收到异常信封）" },
        { key: "加压方式", value: "每步调查增加危险信号（收据矛盾→老周警告→跟踪→暴雨山道）" },
        { key: "情绪爆点", value: "崖底雏菊——认知彻底颠覆" },
        { key: "情绪释放", value: "部分释放（确认有隐情）后立刻被'轮到我找你'重新加压" },
        { key: "可迁移方式", value: "好奇→不安→震惊→紧张→恐惧→颠覆的六段递进" },
      ],
    },
  ],
  newStoryDirections: [
    {
      newCoreGerm: "实习生发现公司账目异常，追查后反被栽赃",
      suitableType: "职场悬疑",
      protagonistCharacter: "刚入职的审计实习生，做事细致，有正义感",
      antagonistHarmMethod: "先拉拢后栽赃，利用公司流程漏洞",
      guideEntryPoint: "实习生发现一笔对不上的账目，金额恰好是上司的生日",
      payPointDirection: "从查账者变为被查者，被栽赃挪用公款",
      difference: "职场背景替代丧父背景，账目替代信封，但保留了'调查者反被猎杀'的核心",
      risk: "职场细节需要真实感，不能太悬浮；反派动机要合理",
    },
    {
      newCoreGerm: "医学生发现导师论文数据造假，举报后反被退学",
      suitableType: "校园悬疑",
      protagonistCharacter: "医学研究生，数据敏感，较真",
      antagonistHarmMethod: "学术霸权+人际关系孤立+篡改实验记录",
      guideEntryPoint: "研究生复现导师论文实验时发现数据对不上",
      payPointDirection: "从举报者变为被举报者，被指控学术不端",
      difference: "学术背景替代执法背景，数据造假替代死亡真相，但保留了信息差递进",
      risk: "学术细节需要准确，反派不能太脸谱化",
    },
    {
      newCoreGerm: "记者调查失踪案，发现自己是最后一个见到失踪者的人",
      suitableType: "社会悬疑",
      protagonistCharacter: "调查记者，执着，有创伤",
      antagonistHarmMethod: "舆论操控+证据篡改+人证收买",
      guideEntryPoint: "记者收到匿名线索调查一起失踪案",
      payPointDirection: "发现所有证据都指向自己，从调查者变为嫌疑人",
      difference: "记者背景替代亡父子女背景，失踪案替代死亡案，但保留了角色反转",
      risk: "反转不能太突兀，需要前期铺垫合理的记忆空白",
    },
  ],
  recommendedDirection: "方向一：实习生发现公司账目异常",
  recommendationReason:
    "职场背景最接地气，受众最广，'账目金额是上司生日'的细节既有悬念又合理，栽赃反转自然，适合盐言故事/番茄短篇的平台调性。",
  selfCheck: {
    coreAttraction: "从追查者变为被追查者的身份反转，用信息差递进驱动付费。",
    infoGapToPayPoint: "已知→隐藏→误判→反转苗头→接近揭开，每一步都有具体'事'推动，信息差撑到最后一段才揭开。",
    chapterProgression: "导语制造悬念→调查发现矛盾→对峙揭露真相，每段都有处境变化和情绪变化。",
    emotionProgression: "好奇→不安→震惊→紧张→恐惧→颠覆，六段递进，每段都有新危险信号加压。",
    skeletonTransferable: "骨架换人物、换场景、换题材后完全成立，核心是'调查者反被猎杀'的角色反转。",
  },
};

// ===== 人设分析 mock =====
const MOCK_CHARACTER: CharacterAnalysis = {
  characterList: {
    bookName: "亡父来信",
    genre: "悬疑/推理短篇",
    coreCharacterAttraction: "执念型调查者与隐藏型反派的对峙",
    totalCharacters: "3",
    characters: [
      {
        name: "主人公'我'",
        narrativeRole: "主人公",
        actionRole: "主动型",
        storyFunction: "推动调查进展，承载读者视角和情绪",
        tier: "核心人物",
        needsFullAnalysis: true,
      },
      {
        name: "交警老周",
        narrativeRole: "反派/隐藏施害者",
        actionRole: "转变型（从旁观者到阻碍者到施害者）",
        storyFunction: "制造信息差，阻碍调查，最终暴露身份",
        tier: "核心人物",
        needsFullAnalysis: true,
      },
      {
        name: "加油站老板",
        narrativeRole: "关键配角/信息提供者",
        actionRole: "功能型",
        storyFunction: "提供关键线索（父亲回头看了三次），推动调查",
        tier: "关键配角",
        needsFullAnalysis: false,
      },
    ],
  },
  mechanismTables: [
    {
      name: "主人公'我'",
      narrativeRole: "主人公",
      surfaceIdentity: "独居的亡父子女，职业未明",
      deepSituation: "七年未走出丧父创伤，对父亲死因有深层执念，处于信息孤岛",
      coreDesire: "查明父亲真实死因",
      coreFear: "害怕父亲死因是谎言，害怕自己查不到真相就被害",
      biggestWeakness: "丧父创伤——一旦触及父亲相关线索就无法理性判断风险",
      bottomLineTrigger: "加油站收据证明父亲死因有疑点，无法再接受'意外'结论",
      actionPattern: "主动型——发现线索立刻行动（翻找旧物、拨打电话、驱车调查）",
      relationshipImbalance: "老周掌握资源和信息优势，主人公处于信息劣势但掌握执念优势",
      emotionFunction: "让读者心疼（丧父创伤）+佩服（不畏威胁）+紧张（独自调查）",
      satisfactionFunction: "兑现认知反转的爽点（崖底雏菊发现）",
      characterArc: "从被动接受'意外死亡'结论 → 主动追查真相 → 被猎杀后必须反击",
      transferableIdentity: "任何创伤驱动的执念型调查者（记者、医生、审计员等）",
      transferableRelationship: "与掌握权力的隐藏反派的关系",
      nonReplicableDetails: "亡父子女身份、山道事故、加油站收据、七年时间跨度",
      protagonistExtra: {
        initialLowPosition: "独居、七年创伤、信息孤岛、无权无势",
        whyNotCounterFirst: "七年前没有异常信息触发追查，官方结论看似无懈可击",
        realPainPoint: "七年信仰的'意外死亡'结论被推翻，父亲可能被害",
        enduranceBoundary: "老周说'别查了'时本可以停手，但收据矛盾让忍耐到达极限",
        counterAbilitySource: "观察力（发现收据）+行动力（驱车调查）+执念（不畏威胁）",
        firstAwakeningEvent: "发现加油站收据日期和地点与事故矛盾",
        trueBoundaryCrossEvent: "被老周跟踪后仍继续前往山道",
        bestAction: "暴雨中明知被跟踪仍开往山道——体现执念压过恐惧",
        highlightAction: "崖底发现雏菊而非车残骸——认知彻底颠覆",
        readerFollowReason: "丧父创伤引发共情，执念和不畏威胁引发敬佩",
      },
    },
    {
      name: "交警老周",
      narrativeRole: "反派/隐藏施害者",
      surfaceIdentity: "处理事故的交警",
      deepSituation: "掌握父亲死因真相，七年来一直在隐瞒，可能是施害者或同谋",
      coreDesire: "保住秘密，不被追查",
      coreFear: "害怕真相曝光，害怕失去权力和自由",
      biggestWeakness: "低估了主人公的执念和行动力",
      bottomLineTrigger: "主人公拨通电话询问事故——从旁观者转为阻碍者",
      actionPattern: "压制型——先用言语压制（'别查了'），再用行为恐吓（跟踪），最后直接威胁",
      relationshipImbalance: "老周掌握执法权和信息优势，主人公处于劣势",
      emotionFunction: "让读者愤怒（滥用职权）+不安（随时可能加害）+震惊（身份揭露）",
      satisfactionFunction: "制造虐点（隐瞒真相、威胁主人公）→ 兑现爽点（身份被揭露）",
      characterArc: "从看似中立的旁观者 → 阻碍者 → 跟踪者 → 暴露的施害者",
      transferableIdentity: "任何掌握权力的隐藏反派（上司、导师、官员等）",
      transferableRelationship: "与调查者的权力不对等关系",
      nonReplicableDetails: "交警身份、处理事故的具体职责、'别查了'的台词",
      antagonistExtra: {
        harmMethod: "言语压制（'别查了'）+行为恐吓（跟踪）+直接威胁（'轮到我找你'）",
        harmLogic: "利用执法权隐瞒证据，利用信息差操控主人公",
        whyDare: "他是执法者，掌握资源和信息优势，认为主人公无力反抗",
        misjudgment: "误判主人公会因恐惧而放弃追查",
        readerDislikeReason: "滥用职权、虚伪关心（'有些事你别查了'假装好意）、冷血监视",
        distinctiveness: "从'别查了'的伪善到'轮到我找你'的赤裸威胁，反差极大",
        grounded: "足够接地气——交警是日常可见的职业，滥用职权有现实基础",
        lostWhere: "低估了主人公的执念，跟踪时暴露了身份",
        karmaMatches: "从隐瞒者变为猎杀者，威胁升级与前文恶行对应",
      },
    },
    {
      name: "加油站老板",
      narrativeRole: "关键配角/信息提供者",
      surfaceIdentity: "加油站经营者",
      deepSituation: "无深层困境，纯功能角色",
      coreDesire: "无",
      coreFear: "无",
      biggestWeakness: "无",
      bottomLineTrigger: "无",
      actionPattern: "被动型——被询问时提供信息",
      relationshipImbalance: "无权力失衡",
      emotionFunction: "提供线索后让读者紧张升级（'回头看了三次'暗示父亲有预感）",
      satisfactionFunction: "推动调查进展",
      characterArc: "无弧光，纯功能角色",
      transferableIdentity: "任何掌握关键信息的功能角色（保安、店员、邻居等）",
      transferableRelationship: "与调查者的信息提供关系",
      nonReplicableDetails: "加油站老板身份、'回头看了三次'的细节",
    },
  ],
  biographies: [
    {
      name: "主人公'我'",
      role: "主人公",
      biography:
        "独居的亡父子女，七年前父亲在山道事故中去世，官方结论是滑坡意外。七年来一直生活在丧父创伤中，独居、信息封闭。直到收到一封写错名字的信，信中声称'父亲不是意外死的'，创伤被重新撕开。发现加油站收据矛盾后，执念压过恐惧，独自驱车调查。在暴雨山道被老周跟踪，崖底发现雏菊而非车残骸，彻底推翻事故结论。最终收到'轮到我找你'的威胁，从追查者变为被追查者。主人公的核心驱动力是丧父创伤——对父亲死因的执念让她不畏威胁，但也让她在关键时刻可能失去理性判断。",
    },
    {
      name: "交警老周",
      role: "反派/隐藏施害者",
      biography:
        "七年前处理父亲事故的交警，掌握事故真相但一直隐瞒。可能是施害者或同谋。七年来以'中立旁观者'面目出现，当主人公拨通电话询问时，从伪善的'别查了'转为跟踪和威胁。老周的深层恐惧是真相曝光，他的加害逻辑是利用执法权隐瞒证据、利用信息差操控主人公。他低估了主人公的执念，在跟踪时暴露了身份。最终从隐瞒者升级为猎杀者，发出'轮到我找你'的威胁。",
    },
    {
      name: "加油站老板",
      role: "关键配角",
      biography:
        "三百公里外加油站的经营者，七年前见过主人公的父亲。被询问时提供了关键线索：父亲当天上车前回头看了三次，暗示有预感。纯功能角色，推动调查进展。",
    },
  ],
  reusableCards: [
    {
      cardName: "创伤驱动的执念型调查者",
      oneLineCharacter: "因创伤而执念，因执念而不畏威胁的调查者",
      suitableGenres: ["悬疑", "推理", "社会悬疑", "职场悬疑"],
      commonPainPoints: ["未愈合的创伤被重新撕开", "调查中步步涉险", "信息劣势下的无力感"],
      commonSatisfactionPoints: ["发现关键线索的快感", "真相浮出水面的认知反转", "不畏威胁的高光时刻"],
      transferableIdentities: ["记者", "审计员", "医学生", "律师", "社工"],
      transferableRelationships: ["与掌握权力的隐藏反派", "与提供线索的功能配角"],
      commonOpening: "收到异常信息触发创伤记忆，开始调查",
      commonHighlightAction: "明知危险仍独自前往关键地点调查",
      commonAntagonistPressure: "言语压制+行为恐吓+直接威胁，逐步升级",
      suitableAntagonists: ["滥用职权的隐藏反派", "伪善的权力掌握者"],
      avoidanceReminder: "创伤来源不能照搬亡父，调查场景不能照搬山道，反派身份不能照搬交警",
    },
    {
      cardName: "伪善的隐藏型反派",
      oneLineCharacter: "以中立面目出现，掌握权力和信息优势，逐步暴露施害者身份",
      suitableGenres: ["悬疑", "惊悚", "权谋", "社会悬疑"],
      commonPainPoints: ["伪善的关心让调查者放松警惕", "滥用职权制造信息差", "逐步升级的威胁"],
      commonSatisfactionPoints: ["身份揭露的震惊反转", "伪善面具被撕下的快感"],
      transferableIdentities: ["上司", "导师", "官员", "医生", "律师"],
      transferableRelationships: ["与调查者的权力不对等关系", "与真相的隐瞒关系"],
      commonOpening: "以中立或善意面目出现，给出'为你好'的建议",
      commonHighlightAction: "跟踪/监视暴露身份，从伪善转为赤裸威胁",
      commonAntagonistPressure: "言语压制→行为恐吓→直接威胁，三级升级",
      suitableAntagonists: ["执念型调查者", "正义感驱动的普通人"],
      avoidanceReminder: "反派身份不能照搬交警，'别查了'的台词不能照搬，跟踪场景不能照搬山道",
    },
  ],
  relationships: [
    {
      relationshipName: "调查者与隐藏施害者",
      originalRelationship: "主人公与交警老周：被调查者遗属与事故处理者",
      abstractRelationship: "信息劣势的调查者与权力优势的隐藏施害者",
      relationshipImbalance: "老周掌握执法权和信息优势，主人公只有执念和观察力",
      conflictEngine: "主人公每步调查都触及老周隐瞒的真相，老周逐步升级压制手段",
      emotionSellingPoint: "伪善关心→身份揭露的反转震撼+调查者不畏威胁的敬佩",
      transferableRelationships: [
        "记者与隐藏腐败官员",
        "审计员与财务总监",
        "研究生与导师",
        "护士与主任医师",
      ],
      nonReplicableParts: ["交警处理事故的具体职责", "'别查了'的台词", "山道跟踪场景"],
    },
    {
      relationshipName: "调查者与信息提供者",
      originalRelationship: "主人公与加油站老板：调查者与线索提供者",
      abstractRelationship: "调查者与掌握关键信息的功能角色",
      relationshipImbalance: "无权力失衡，纯信息交换",
      conflictEngine: "信息提供者的回忆推动调查进展",
      emotionSellingPoint: "关键线索带来的紧张升级+调查突破的满足",
      transferableRelationships: [
        "记者与保安",
        "审计员与前台",
        "研究生与实验室管理员",
      ],
      nonReplicableParts: ["加油站老板身份", "'回头看了三次'的细节"],
    },
  ],
};

// ===== 完整 AnalysisResult mock =====
export const MOCK_ANALYSIS: AnalysisResult = {
  plot: {
    status: "loaded",
    data: MOCK_PLOT,
    durationMs: 15200,
  },
  character: {
    status: "loaded",
    data: MOCK_CHARACTER,
    durationMs: 12800,
  },
  meta: {
    totalMs: 15200,
    tokens: 4820,
    degraded: false,
  },
};
